### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by jaipalvyza** [ChillarAnand/stocktrends#3]
Hi Anand,
I am trying to use stocktrend library to plot renko.
in my program i am getting memeory error".

[renktest.txt](https://github.com/ChillarAnand/stocktrends/files/2363466/renktest.txt)

please let me know if further details required.

**Comment by jaipalvyza** [comment]
Traceback (most recent call last):
  File "C:\Users\JOY\Desktop\kiteconnect\Database\Crude_Renk_0905.py", line 148, in <module>
    main()
  File "C:\Users\JOY\Desktop\kiteconnect\Database\Crude_Renk_0905.py", line 131, in main
    testdata = renko.get_ohlc_data()
  File "C:\Users\JOY\Desktop\kiteconnect\Database\stocktrends\indicators.py", line 37, in get_ohlc_data
    self.period_close_bricks()
  File "C:\Users\JOY\Desktop\kiteconnect\Database\stocktrends\indicators.py", line 83, in period_close_bricks
    data.append(r)
MemoryError

**Comment by ChillarAnand** [comment]
@jaipalvyza Thanks for creating bug report.

Can you tell the size of dateframe your are loading and your system memory?

**Comment by ChillarAnand** [comment]
I have tested with ~4000 rows csv, but it seems working fine. Can you share that data you are using?

Right now calculations are bit inefficient but with 2000 rows and 8GB memory, it shouldn't be throwing this error.

**Comment by ChillarAnand** [comment]
Closing this issue. If you are still facing it, please re-open it.
